# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa3e0b2d6dbd27b464981b445751e0c891e1d39580ac009bf5992beebe52ccf874805bc2d147ba2320e497c3fe4c7c5208c271da54e3cd923d21315fb30532e6

test:
  secret_key_base: 9089a02ee5b8a603012a46e9a4d3cf4ed411a0cd08594b9b00d941e109afb00594013f10fdd6c74ccd1c6d289e11389b448fdf646b2e879fac4a5ba737b3150a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
